# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'weather-message' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'Firebase/Analytics'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'SVProgressHUD'
    pod 'ChameleonFramework'
    pod 'Google-Mobile-Ads-SDK'
    pod 'mopub-ios-sdk'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
