# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FaceDetector' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceDetector
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionFaceModel'
    
  target 'FaceDetectorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FaceDetectorUITests' do
    # Pods for testing
  end

end
